import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/Sidebar";
import { Header } from "@/components/Header";
import { AIPanel } from "@/components/AIPanel";
import { SimulationProvider } from "@/context/SimulationContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex bg-gray-50`}
      >
        <SimulationProvider>
          <Sidebar />
          <div className="flex-1 flex flex-col min-h-screen isolate overflow-hidden">
            <Header />
            <main className="flex-1 overflow-auto bg-gray-50/50 relative">
              {children}
            </main>
          </div>
          <AIPanel />
        </SimulationProvider>
      </body>
    </html>
  );
}
