import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/Sidebar";
import { Header } from "@/components/Header";
import { AIPanel } from "@/components/AIPanel";
import { SimulationProvider } from "@/context/SimulationContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900`}
      >
        <SimulationProvider>
          <div className="flex h-screen w-screen overflow-hidden">
            <Sidebar />
            <div className="flex-1 flex flex-col h-full isolate overflow-hidden bg-gray-50">
              <Header />
              <main className="flex-1 overflow-y-auto relative p-0 m-0 w-full h-full">
                {children}
              </main>
            </div>
            <AIPanel />
          </div>
        </SimulationProvider>
      </body>
    </html>
  );
}
